# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Qiscus_VideoCall_IOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Qiscus_VideoCall_IOS
#  pod 'QiscusRTC', '0.1.8'
  pod 'QiscusRTC', :git => 'http://github.com/qiscus/QiscusRTC.git', :branch => 'master'

#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#              config.build_settings['ENABLE_BITCODE'] = 'NO'
#          end
#      end
#  end

end
